[central_load_plan]
# non-recursive glob search
source_glob = instance/data/central-load-plan/samples/*
# move each file to this location after processing
move_to = 

[smtp]
host = localhost:2525

[emailmessage]
from = ...
subject = .format passed data from schema loaded {somevar}

[emailmessage_8C]
# ATI
to = ...

[emailmessage_GB]
# ABX
to = ...
