[central_load_plan]
# non-recursive glob search
source_glob =
# move each file to this location after processing
move_to = 

[smtp]
# smtplib.SMTP arguments
host =

[emailmessage]
# base section for company specific sections
# all emailmessage sections' values are `.format` called with the data loaded
# from schema. probably only useful for subject
from =
subject =

[emailmessage_iata_company_code]
# a section for every company that can be encountered must exist

[oracle]
oracle_lib_dir =
drivername = 
database =
host = 
port =

[oracle_iata_company_code]
username =
password =
